CREATE TABLE IF NOT EXISTS public.words (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 啟用 Row Level Security (RLS)
ALTER TABLE public.words ENABLE ROW LEVEL SECURITY;

-- 刪除已存在的相同政策（避免重複執行報錯）
DROP POLICY IF EXISTS "Allow public select" ON public.words;
DROP POLICY IF EXISTS "Allow public insert" ON public.words;

-- 允許任何人讀取詞彙
CREATE POLICY "Allow public select" ON public.words
    FOR SELECT USING (true);

-- 允許任何人新增詞彙
CREATE POLICY "Allow public insert" ON public.words
    FOR INSERT WITH CHECK (true);
